apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stocktrader

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: registry.dizzyman.nl/stocktrader
    newTag: "1.3.14"
